---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app.kubernetes.io/name: load-balancer-example
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort:  {{ .Values.service.targetPort }}
  selector:
    app.kubernetes.io/name: load-balancer-example
