apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: oc-taskrun
spec:
  serviceAccountName: deployer
  params:
    - name: ARGS
      value:
        - get
        - pods
  taskRef:
    name: openshift-client
