# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

superValue: somevalue

resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      cpu: 100m
      memory: 128Mi

service:
  port: 8080
  targetPort: 8080
