---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-example
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-example
    spec:
      containers:
      - image: gcr.io/google-samples/node-hello:1.0
        name: hello-world
        ports:
        - containerPort: 8080

        # Secret env, task 1
        env:
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: prod-db-secret
              key: password

        # configmap volume, task 2
        volumeMounts:
          - name: bootstrap
            mountPath: /config
      volumes:
        - name: bootstrap
          configMap:
            name: cm-bootstrap
